apiVersion: v1
kind: Service
metadata: 
  name: openmrs-svc
  labels:
    service: openmrs
spec:
  ports:
    - name: openmrs-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: openmrs
  type: LoadBalancer    
